name: libphase
channels:
  - defaults
  - conda-forge
  - anaconda
  - quantstack
  - nlesc
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - ipython
  - jupyter
  - flake8
  - click
  - tqdm
  - pandas
  - matplotlib
  - cmake
  - seaborn
  - pip
  - zlib
  - pip:
    - clickutil
    - pixiedust
